config/routes.rb
SecondhandCars::Application.routes.draw do
  get "car/" => 'car#index', :as => :list
  get "car/new" => 'car#new'
  post "car/create" => 'car#create', :as => :cars
  get "car/:id" => 'car#details', :as => :car_details
  get "car/:id/edit" => 'car#edit', :as => :car_edit
  put "car/:id/update" => 'car#update', :as => :car
  post "/search" => 'application#search'
  get "/search" => 'application#search'

  match 'home/getmodels' => 'application#get_models'

  root :to => 'application#index'

  resources :sessions, only: [:create, :destroy]
  match '/signout', to: 'sessions#destroy', via: :delete

end

app/models/car.rb
class Car < ActiveRecord::Base
   attr_accessible :description, :doors, :price, :seats, :year, :owner_id, :car_model_id, :sold, :mileage, :transmission, :type, :color, :capacity
  belongs_to :car_model
  belongs_to :owner
	validates :description, :year, :price, :car_model, :presence => true
	validates :doors, :seats, :mileage, :capacity, :numericality => { :only_integer => true }, :allow_nil => true
 	validates :seats, :numericality => { :only_integer => true }, :allow_nil => true
  validates :transmission, :inclusion => { :in => %w(Manual Automatic) }, :allow_nil => true
  validates :type, :inclusion => { :in => %w(Sedan Sports SUV Coupe Caporle Van Hatchback Station 4WD) }, :allow_nil => true
	validates_associated :owner
  validates :owner, :presence => true

  def make_name
    return self.car_model.make_name
  end

  def model_name
    return self.car_model.name
  end

  def owner_name
    return self.owner.name
  end

  def owner_phone
    return self.owner.get_contact
  end

  def make
    return self.car_model.make_id unless self.car_model.nil?
  end

  def editable_by(user)
    return !user.nil? && user.owner_id == self.owner_id
  end

  def self.view(id)
    car = Car.find(id)
    return if car.nil?
    car.increment!(:visited)
    return car
  end

  def self.match(criteria)
    criteria = criteria.delete_if {|key, value| value.blank? }
    criteria.delete(:car_models) if criteria[:car_models][:make_id].blank?
    price_from = criteria[:price_from].to_i
    price_to = criteria[:price_to].to_i
    criteria.delete(:price_from)
    criteria.delete(:price_to)
    criteria[:price] = price_from..price_to if price_from > 0 && price_to > 0
    criteria[:price] = price_from..10000000 if price_from > 0 && price_to == 0
    criteria[:price] = 0..price_to if price_from == 0 && price_to > 0
    criteria[:sold] = false
    result = Car.find(:all, :conditions => criteria, :joins => [:car_model])
  end

  def self.list_cars(filters = {})
    cars = Car.find(:all, :conditions => {:sold => false})
    if(!filters[:car_model].blank?)
      cars = cars.select { |c| c.model_name == filters[:car_model] }
    elsif(!filters[:make].blank?)
      cars = cars.select { |c| c.make_name == filters[:make] }
    end
    cars = cars.select { |c| c.year.to_s == filters[:year] } unless filters[:year].blank?
    return cars
  end
end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
  attr_accessible :name, :make_id
  belongs_to :make

  def make_name
    return self.make.name
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  attr_accessible :name
  has_many :car_model
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  attr_accessible :email, :mobile, :name, :phone
  has_one :user

  before_save { |owner| owner.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :mobile, presence: true
  validates :email, presence: true,
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates_associated :user

  def get_contact
    if !self.mobile.nil?
      return self.mobile
    else
      return self.phone
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :owner_id, :password, :password_confirmation
  belongs_to :owner
  has_secure_password
  validates :owner_id, :presence => true
  validates :password, :password_confirmation, :presence => true, :on => :create

  def name
    return owner.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def get_models
    if(params[:make_name])
      render :json => Make.find_by_name(params[:make_name]).car_model.to_json
    elsif(params[:make_id])
      render :json => Make.find(params[:make_id]).car_model.to_json
    end
  end

  def index
    @latest = Car.find(:all, :conditions => { :sold => false }, :order => 'created_at DESC', :limit => 5)
    @most_viewed = Car.find(:all, :conditions => { :sold => false }, :order => 'visited DESC', :limit => 5)
  end

  def search
    @cars = nil
    if request.method == "POST"
      @cars = Car.match(params[:search])
      flash[:notice] = "No cars matching criteria" if @cars.blank?
    end
  end
end

app/controllers/car_controller.rb
class CarController < ApplicationController
  def index
    @cars = Car.list_cars(params)
  end

  def details
    id = params[:id]
    if id.nil?
      flash[:error] = "Missing data"
      redirect_to(:action => :index)
    end
    @car = Car.view(id)
    if(@car.nil?)
      flash[:error] = "No such car"
      redirect_to :action => :index
    end
  end

  def new
    @makes = Make.all
    @car = Car.new
    @car.owner = Owner.new unless signed_in?
    @car.owner_id = current_user.owner_id if signed_in?
  end

  def edit
    id = params[:id]
    if id.nil?
      flash[:error] = "Missing data"
      redirect_to :action => :index
    end

    @car = Car.find(id) if @car.nil?
    if @car.nil?
      flash[:error] = "No such car"
      redirect_to :action => :index
    end
    if !@car.editable_by(current_user)
      flash[:error] = "Don't have access to car"
      redirect_to :action => :index
    end

    @makes = Make.all
    @car_models = CarModel.where(:make_id => @car.make)
  end

  def create
    @car = Car.new(params[:car])
    if(!signed_in?)
      owner = Owner.new(params[:owner])
      owner.user = User.new(params[:user])
      @car.owner = owner
    end
    create_or_update
    render 'new' if !@car.valid?
  end

  def update
    id = params[:car][:id]
    @car = Car.find(id)
    @car.assign_attributes(params[:car])
    create_or_update
    render 'edit' if !@car.valid?
  end

private
  def create_or_update
    @car.doors = nil if @car.doors.blank?
    @car.seats = nil if @car.seats.blank?
    if @car.valid?
      @car.save
      flash[:success] = "Cas saved successfully"
      redirect_to :action => :details, :id => @car
    end
    @makes = Make.all
    @car_models = CarModel.where(:make_id => @car.make)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    owner = Owner.find_by_email(params[:email])
    if(owner && owner.user.authenticate(params[:password]))
      sign_in(owner.user)
      flash[:success] = "Login successful"
    else
      flash[:error] = "Wrong email or password"
    end
    redirect_to '/'
  end

  def destroy
    sign_out
    flash[:success] = "Logout successful"
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def list_makes(name = "make", use_id = false)
    if use_id
      select_tag name, options_from_collection_for_select(Make.all, "id", "name"), :include_blank => true
    else  
      select_tag name, options_from_collection_for_select(Make.all, "name", "name"), :include_blank => true
    end
  end
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.owner_id
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_owner_id(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/views/application/_form.html.erb
<% if @cars.blank? %>
  <form method="post" action="/search">
    <table>
      <tr>
        <td><label>Make</label></td>
        <td><%= list_makes "search[car_models[make_id]]", true %></td>
      </tr>
      <tr>
        <td><label>Model</label></td>
        <td><select id="search_car_model" name="search[car_model_id]"></select></td>
      </tr>
      <tr>
        <td><label>Year</label></td>
        <td><%= select_tag "search[year]", options_for_select(1992..(Date.today.year)), :include_blank => true %></td>
      </tr>
      <tr>
        <td><label>Doors</label></td>
        <td><input type="text" name="search[doors]" />
      </tr>
      <tr>
        <td><label>Seats</label></td>
        <td><input type="text" name="search[seats]" />
      </tr>
      <tr>
        <td><label>Price</label></td>
        <td>From: <input type="text" name="search[price_from]" /> - 
        To  : <input type="text" name="search[price_to]" /></td>
      </tr>
      <tr>
        <td><input type="submit" value="Search" /></td>
      </tr>
    </table>
  </form>
  <script type="text/javascript">
    $(function() {
      $('#search_car_models_make_id').change(function() {
        $('#car_model').empty();
        if($(this).val() == '' || $(this).val() == undefined) return false;
        $.get('/home/getmodels/', { make_id: $(this).val() }, function(data) {
          $('#search_car_model').append('<option></option>');
          for(i = 0; i < data.length; i++) {
            $('#search_car_model').append('<option value="' + data[i].id + '">' + data[i].name + '</option>');
          }
        });
      });
    });
  </script>
<% end %>

app/views/application/_list.html.erb
<% unless @cars.blank? %>
  <table>
    <% @cars.each do |car| %>
      <tr>
        <td>
          <%= car.make_name %> -
          <%= car.model_name %> -
          <%= car.year %> -
          <%= car.description %> -
          <%= car.owner_name %> -
          <%= car.owner_phone %> -
          <%= car.price %> LE
          <%= link_to 'Details', car_details_path(car) %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/application/index.html.erb
<h2>Latest Cars</h2>
<ul class="listing">
  <% @latest.each do |c| %>
    <li><%= c.model_name %> - <%= c.description %> - <%= link_to 'Details', car_details_path(c) %></li>
  <% end %>
</ul>

<h2>Most Viewed</h2>
<ul class="listing">
  <% @most_viewed.each do |c| %>
    <li><%= c.model_name %> - <%= c.description %> - <%= link_to 'Details', car_details_path(c) %></li>
  <% end %>
</ul>

<%= link_to 'Full List', list_path %>

app/views/application/search.html.erb
<% if @cars.blank? %>
  <%= render 'form' %>
<% else %>
  <%= render 'list' %>
<% end %>

<%= link_to "Return to List", list_path %>

app/views/car/_form.html.erb
<%= form_for(@car) do |f| %>
  <%= f.hidden_field :id %>
  <%= f.hidden_field :owner_id %>
  <%= f.hidden_field :sold %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@car.errors.count, "error") %>.
      </div>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li>* <%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend>Car Details</legend>
    <table>
      <tr>
        <th>Make</th>
        <td><%= select_tag "make_id", options_from_collection_for_select(@makes, "id", "name", @car.make), :include_blank => true %></td>
      </tr>
      <tr>
        <th>Model</th>
        <td>
          <% if @car_models.nil? %>
            <select id="car_car_model_id" name="car[car_model_id]"></select>
          <% else %>
            <%= select_tag "car[car_model_id]", options_from_collection_for_select(@car_models, "id", "name", @car.car_model_id), :include_blank => true %></td>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>Year</th>
        <td><%= select_tag "car[year]", options_for_select(1992..(Date.today.year), @car.year), :include_blank => true %></td>
      </tr>
      <tr>
        <th>Description</th>
        <td><%= f.text_area :description, :rows => 5 %></td>
      </tr>
      <tr>
        <th>Price</th>
        <td><%= f.text_field :price %></td>
      </tr>
    </table>
    <a href="#" onclick="javascript: $(this).next().toggle(); return false;">More details</a>
    <table style="display:none">
      <tr>
        <th>Doors</th>
        <td><%= f.text_field :doors %></td>
      </tr>
      <tr>
        <th>Seats</th>
        <td><%= f.text_field :seats %></td>
      </tr>
      <tr>
        <th>Type</th>
        <td><%= select_tag "type", options_for_select(%w(Sedan Sports SUV Coupe Caporle Van Hatchback Station 4WD), @car.type), :include_blank => true %></td>
      </tr>
      <tr>
        <th>Transmission</th>
        <td><%= select_tag "transmission", options_for_select(%w(Manual Automatic), @car.transmission), :include_blank => true %></td>
      </tr>
      <tr>
        <th>Mileage</th>
        <td><%= f.text_field :mileage %></td>
      </tr>
      <tr>
        <th>capacity</th>
        <td><%= f.text_field :capacity %></td>
      </tr>
      <tr>
        <th>Color</th>
        <td><%= f.text_field :color %></td>
      </tr>
    </table>
  </fieldset>
  <% if @car.new_record? && !signed_in? %>
    <!-- comment befor -->
    <%= render :partial => 'owner/owner_form', :locals => { :owner => @car.owner } %>
    <!-- comment after -->
  <% end %>
  <!-- comment submit -->
  <%= f.submit "Save" %>
<% end %>

app/views/car/details.html.erb
<h2><%= @car.make_name %> - <%= @car.model_name %></h2>
<h3><%= @car.year %></h3>

<table class="car_details">
  <tr>
    <th>Description</th>
    <td><%= @car.description %></td>
  </tr>
  <tr>
    <th>Price</th>
    <td><%= @car.price %>LE</td>
  </tr>
  <% if !@car.type.blank? %>
    <tr>
      <th>Type</th>
      <td><%= @car.type %></td>
    </tr>
  <% end %>
  <% if !@car.transmission.blank? %>
    <tr>
      <th>Transmission</th>
      <td><%= @car.transmisson %></td>
    </tr>
  <% end %>
  <% if !@car.capacity.blank? %>
    <tr>
      <th>Capacity</th>
      <td><%= @car.capacity %></td>
    </tr>
  <% end %>
  <% if !@car.mileage.blank? %>
    <tr>
      <th>Mileage</th>
      <td><%= @car.mileage %></td>
    </tr>
  <% end %>
  <% if !@car.doors.blank? %>
    <tr>
      <th>Doors</th>
      <td><%= @car.doors %></td>
    </tr>
  <% end %>
  <% if !@car.seats.blank? %>
    <tr>
      <th>Seats</th>
      <td><%= @car.seats %></td>
    </tr>
  <% end %>
  <% if !@car.color.blank? %>
    <tr>
      <th>Color</th>
      <td><%= @car.color %></td>
    </tr>
  <% end %>
</table>

<%= render :partial => "owner/owner_contact", :locals => { :owner => @car.owner } %>
<% if @car.editable_by(current_user) %>
  <%= link_to 'Edit', car_edit_path(@car) %>
<% end %>
<%= link_to 'Return to List', list_path %>

app/views/car/edit.html.erb
<h2>Edit Car</h2>

<%= render :partial => 'form' %>

<%= link_to 'Return to List', list_path %>

app/views/car/index.html.erb
<h2>Available Cars</h2>
<table class="car_list">
  <% @cars.each do |car| %>
    <tr>
      <td>
        <%= car.make_name %>
      </td>
      <td>
        <%= car.model_name %>
      </td>
      <td>
        <%= car.year %>
      </td>
      <td>
        <%= car.description %>
      </td>
      <td>
        <%= car.owner_name %>
      </td>
      <td>
        <%= car.owner_phone %>
      </td>
      <td>
        <%= car.price %> LE
      </td>
      <td>
        <%= link_to 'Details', car_details_path(car) %>
      </td>
    </tr>
  <% end %>
</table>
<% if @cars.empty? %>
  <h4>No cars available</h4>
<% end %>
<%= link_to 'Create Car', car_new_path %>

app/views/car/new.html.erb
<h2>Create Car</h2>

<%= render :partial => 'form' %>

<%= link_to 'Return to List', list_path %>

app/views/layouts/_search.html.erb
<form id="search_form" method="get" action="/car">
  <table>
    <tr>
      <td><label>Make</label></td>
      <td><%= list_makes %></td>
    </tr>
    <tr>
      <td><label>Model</label></td>
      <td><select id="car_model" name="car_model"></select></td>
    </tr>
    <tr>
      <td><label>Year</label></td>
      <td><%= select_tag "year", options_for_select(1992..(Date.today.year)), :include_blank => true %></td>
    </tr>
    <tr>
      <td><input type="submit" value="Filter" /></td>
      <td><a href="/search">Advanced Search</a></td>
    </tr>
  </table>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Secondhand Cars</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header style="clear: both">
    <div class="login">
      <% if signed_in? %>
        <%= current_user.name %> - <%= link_to "Logout", signout_path, method: "delete" %>
      <% else %>
        <%= form_for(:sessions, :url => sessions_path) do |f| %>
        <a href="#" onclick="$(this).next().toggle(); return false;">Login</a>
        <table style="display: none">
          <tr>
            <td>Email</td>
            <td><input type="text" name="email" /></td>
          </tr>
          <tr>
            <td>Password</td>
            <td><input type="password" name="password" /></td>
          </tr>
          <tr><td colspan="2"><input type="submit" value="Login" /></td></tr>
        </table>
        <% end %>
      <% end %>
    </div>
    <h1><%= link_to "Secondhand Cars", root_path %></h1>
  </header>
  <div class="container">
    <%= render :partial => 'layouts/search' %>
    <% if flash[:error] -%>
      <p class='error'><%=h flash[:error] %></p>
    <% end -%>
    <% if flash[:notice] -%>
      <p class='notice'><%=h flash[:notice] %></p>
    <% end -%>
    <% if flash[:success] -%>
      <p class='success'><%=h flash[:success] %></p>
    <% end -%>
    <%= yield %>
  </div>
</body>
</html>

app/views/owner/_owner_contact.html.erb
<fieldset>
  <legend>Owner Details</legend>
  <span style="margin-right: 10%;"><%= owner.name %></span>
  <span style="margin-right: 10%;"><%= owner.mobile %></span>
  <span style="margin-right: 10%;"><%= owner.email %></span>
</fieldset>

app/views/owner/_owner_form.html.erb
<fieldset>
  <legend>Owner Details</legend>
  <table>
    <tr>
      <th>Owner Name</th>
      <td><%= text_field_tag 'owner[name]', owner.name %></td>
    </tr>
    <tr>
      <th>Owner Email</th>
      <td><%= email_field_tag 'owner[email]', owner.email %></td>
    </tr>
    <tr>
      <th>Owner Mobile</th>
      <td><%= text_field_tag 'owner[mobile]', owner.mobile %></td>
    </tr>
    <tr>
      <th>Owner Phone</th>
      <td><%= text_field_tag 'owner[phone]', owner.phone %></td>
    </tr>
    <tr>
      <th>Password</th>
      <td><%= password_field_tag 'user[password]' %></td>
    </tr>
    <tr>
      <th>Confirm</th>
      <td><%= password_field_tag 'user[password_confirmation]' %></td>
    </tr>
  </table>
</fieldset>